name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
     pages: write
     contents: write
     deployments: write
     id-token: write
  
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack
        
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1.0.3
      with:
        # Path of the directory containing the static assets.
        path: dist/ # default is _site/
        # Duration after which artifact will expire in days.
        #retention-days: # optional, default is 1
        
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      deployments: write
      id-token: write
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1.0.10
        with:
         token: ${{ github.token }} # default is ${{ github.token }}
